spring:
  application:
    name: eureka-server
server:
  port: 1111

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 300000
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

logging:
  path: logs/eureka


#应用名称
#spring.application.name=eureka-server
#server.port=1111

#eureka.instance.hostname=localhost

#eureka.server.enable-self-preservation=false
#是否开启客户端（使用eureka）注册操作
#eureka.client.register-with-eureka=false
#不需要检索服务、维护服务实例
#eureka.client.fetch-registry=false
#eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname:localhost}:${eureka.port:1111}/eureka/

#logging.path=logs/generic
#logging.file=${spring.application.name}.log

# 是否开启自我保护
#eureka.server.enable-self-preservation=false
# 清理不健康的服务节点间隔（单位毫秒，默认是60*1000）
#eureka.server.eviction-interval-timer-in-ms=30000

