spring:
      jpa:
           show-sql: true
      datasource:
            url:  jdbc:mysql://localhost:3306/app_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
            username: root
            password: root
