spring:
      jpa:
           show-sql: false
      datasource:
                url:  jdbc:mysql://10.88.2.24:3306/app_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
                username: root
                password: 123456


